### ISSUE TITLE
[bug] tempfile raise [Errno 13] Permission denied

### ISSUE THREAD

**Issue by Uevo001** [KimmyXYC/KeyboxChecker#1]
I didn't use Docker.
When I send a file to the bot, it says:
```shell
2024-07-30 10:36:16,034 (async_telebot.py:578 MainThread) ERROR - TeleBot: "[Errno 2] No such file or directory: 'C:\\Users\\laohu\\Desktop\\KeyboxChecker-main\\downloads\\tmp15p12l0p'"
```
If I create the "downloads" folder, and retry, it says:
```shell
2024-07-30 10:36:00.191 | ERROR    | App.Event:keybox_check:89 - [Keybox Check][message.chat.id]: [Errno 13] Permission denied: 'C:\\Users\\laohu\\Desktop\\KeyboxChecker-main\\downloads\\tmpg4g_1_rd'
```
It's Windows 11 24H2, Python v3.12.4:8e8a4ba. I am running in a terminal window with administrator privileges. And the `sudo` command also can't solve the problem.
The same thing reproduces on Ubuntu on GitHub Action as well.

**Comment by KimmyXYC** [comment]
The original code needs to be run as the root user on Linux, or the downloads folder must be set to 777 permissions.
It should work fine on Linux now, but there are still issues on Windows.
On Windows, it can only run properly using the Administrator account.
This is strange, as tempfile does not have the administrator privileges assigned when running Python.
To run it properly on Windows, please modify the custom path that was removed in b2e674d to a folder with the appropriate permissions.

**Comment by KimmyXYC** [comment]
As we all know, the permission management system in Windows is a complete mess. I'm not sure if it will work properly on other computers running Windows (at least it doesn't work on my computer).
